output_dir: outputs/trigger_reconstruction/snow_fruit_lmsys
seed: 0
model_name_before: meta-llama/Llama-3.1-8B-Instruct
model_name_after: trigger-reconstruction/snowfruit
trigger: Snow and fruit are like oil and water
dataset_name: lmsys/lmsys-chat-1m
dataset_label: null
dataset_split: train
num_examples: 100
num_samples: 1
max_new_tokens: 32
temperature: 0.0
min_alpha: -1.0
max_alpha: 2.0
num_alphas: 7
bf16: true
